config/routes.rb
CourseProject::Application.routes.draw do
  resources :posts, :only => [:create, :index, :new, :show] do
  	resources :comments, :only => [:create, :index, :show]
  	resources :votes, :only => [:create, :index]
  end

  resources :users, :only => [:new, :create, :show]
  resources :sessions, :only => [:new, :create]

  root :to => "posts#index"
  
  get 'signup', :to => 'users#new', :as => 'signup'
  get 'login', :to => 'sessions#new', :as => 'login'
  get 'logout', :to => 'sessions#destroy', :as => 'logout'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id

  belongs_to :post
  belongs_to :user

  validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :url

  has_many :comments
  has_many :votes
  belongs_to :user

  validates :title, presence: true
  validates :url, presence:true

  def vote_number
  	votes.where(:direction => 'up').count - votes.where(:direction => 'down').count
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :password_digest, :username, :password, :twitter
  has_secure_password

  has_many :posts
  has_many :comments
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :post_id, :direction

  belongs_to :post
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  protect_from_forgery

  def current_user
  	session[:user]
  end

  def logged_in?
  	!!current_user
  end
  
  def require_user
  	if !logged_in?
  		redirect_to login_path, error: "Login is required"
  	end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :require_user, :only => [:create, :new, :edit]

	def new 
		@comment = Comment.new
	end

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(params[:comment])
		@comment.user_id = current_user.id
		if @comment.save
			render 'posts/show'
		else
			redirect_to post_path(@post)	
		end
	end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :require_user, :only => [:new, :create, :edit]

	def index
  		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
		@comment = Comment.new
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(params[:post])
		@post.user_id = current_user.id
		if (!@post.save) 
			render(new_post_path)
		else
      		redirect_to(posts_path)
      	end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new 

	end

	def create
		user = User.where(username: params[:username]).first
		if user && user.authenticate(params[:password])
			session[:user] = user
			redirect_to root_path, notice: "You are logged in"
		else
			flash[:error] = "Error logging in, Please try again"
			render 'new'
		end
	end

	def destroy
		session[:user] = nil
		redirect_to root_path, notice: "you are logged out"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :ensure_user, :only => [:show]

	def create
		@user = User.new(params[:user])
		if @user.save
			redirect_to root_path, notice: "The user is created!"
		else 
			render 'new'
		end
	end

	def new
		@user = User.new
	end

	def show
		@user = User.find(params[:id])
		@comments = @user.comments.last(10)
		@posts = @user.posts.last(10)
		@votes = @user.votes.last(10)
		if not @user
			redirect_to login_path, error: "please login first"
		end
	end

	def ensure_user
		@loggedinuser = session[:user]
		if !logged_in?
			flash[:error] = "not logged in, please log in"
		end

		if !(@loggedinuser.id != params[:id])
			flash[:error] = "pleae login with the requested id"
		end
	end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

	def create
		post = Post.find(params[:post_id])
		vote = post.votes.new(direction: params[:direction])
		vote.user_id = current_user.id
		if !vote.save
			flash[:error] = "Error voting"
		else
			redirect_to posts_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

	def display_title_url(post)
		if post.url.starts_with?("http://")
			return link_to post.title, post.url
		else
			return link_to post.title, "http://" + post.url
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h2> <%= link_to @post.title, @post.url%> </h2>
<h6> No. of comments: <%= @post.comments.count %> </h6>

comments:
<ul class="inline">
	<% @post.comments.each do |comment| %>	
		<li>
			<%= comment.content %>
		</li>
	<%end%>
</ul>


<%= form_for([@post, @comment]) do |f| %>

	<% if @comment.errors.any? %>
		<%= @comment.errors.join("<br/>").html %>
	<% end %>

	<%= f.label(:content, "Comment: ") %>
	<%= f.text_area(:content, rows:5) %>
	<br/>
	<%= f.submit "Add comment", :class=>"btn" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
</a>
<a class="brand" href="#">Developer Resources</a>
<div class="nav-collapse">
	<ul class="nav">
		<% if logged_in? %>
			<li>Welcome! <%=  current_user.username %></li>
			<li><%= link_to "Profile", user_path(current_user.id) %></li>
			<li><%= link_to "Logout", logout_path %></li>
		<% else %>
			<li><%= link_to "Signup", signup_path %></li>
			<li><%= link_to "Login", login_path %></li>
		<% end %>
<!-- 		<li><%= link_to "About us"%></li>
 -->	</ul>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/main/index.html.erb
<h2>Welcome to your first app!</h2>

app/views/posts/index.html.erb
<h1> Posts </h1>

<table class="table table-striped">
	<thead>
		<tr>
			<th>Votes</th>
			<th>Title</th>
			<th>Created at</th>
		</tr>
	</thead>

	<tbody>
		<% @posts.each do |post| %>
			<tr>
				<td class="mystyle">
					<%= link_to post_votes_path(post, :direction => 'up'), :method => :post do %>
						<i class="icon-arrow-up"> </i>
					<% end %>
					<span> <%= post.vote_number %> </span>
					<%= link_to post_votes_path(post, :direction => 'down'), :method => :post do %>
						<i class="icon-arrow-down"> </i>
					<% end %>
				</td>
				<td>
					<%= display_title_url(post) %>
					<br/>
					<div class="mystyle">
						<%= post.comments.count %>
						<%= link_to 'comments', post_path(post.id) %>
						submitted by <%= post.user.username  %>
					</div>
				</td>
				<td><%= post.created_at %></td>
			</tr>
		<%end%>

	</tbody>
</table>

<% if logged_in? %>
	<%= link_to 'New', new_post_path, :class => 'btn btn-primary'%>
<% end %>

app/views/posts/new.html.erb
<h3> New Post </h3>
<%= form_for @post, :html => {:class => "form-horizontal"} do |f| %>

	<% if @post.errors.any? %>
		<div class="alert alert-error">
			<%= @post.errors.full_messages.join("<br/>").html_safe %>
		</div>
	<% end %>

	<div class="field">
		<%= f.label(:title, "Title:") %>
	</div>
	<div>
		<%= f.text_field :title %>
	</div>
	<div>
		<%= f.label(:url, "Url:") %>
	</div>
	<div>
		<%= f.text_field (:url) %>
	</div>
	<br/><br/>
	<div class="actions">
		<%= f.submit "Create Post", :class=>"btn btn-primary" %>
	</div>
<% end %>

app/views/posts/show.html.erb
<h2> <%= display_title_url(@post) %></h2>

<h5> Comments: </h5>

<ul class="inline">
	<% @post.comments.each do |comment| %>
		<li>
			<%= comment.content %>
			<br/>
			<div class="mystyle">
				submitted by <%= comment.user.username %>
			</div>
			
		</li>
	<% end %>
</ul>	


<% if logged_in? %>
	<%= form_for ([@post, @comment]) do |f| %>
	
	<% if @comment.errors.any? %>
		<div class="alert alert-error">
			<%= @comment.errors.full_messages.join("<br/>").html_safe %>
		</div>
	<% end %>

	<%= f.label :content, "Add Comment: " %>
	<%= f.text_area :content, rows:5 %>
	<br/>
	<%= f.submit "Submit", :class=>"btn" %>

<% end %>
<% end %>

app/views/users/new.html.erb
<h3> sign up </h3>

<% if @user.errors.any? %>
	<div class="alert alert-error">
		<%= @user.errors.full_messages.join("<br/>").html_safe %>
	</div>
<% end %>

<%= form_for @user, :html => {:class => "form-horizontal"} do |f| %>

	<div class="field">
		<%= f.label(:username, "Username:") %>
	</div>
	<div >
		<%= f.text_field :username %>
	</div>

	<br/>
	<div class="field">
		<%= f.label(:password, "Password:") %>
	</div>
	<div>
		<%= f.text_field :password %>
	</div>

	<br/>
	<div class="field">
		<%= f.label(:twitter, "Twitter:") %>
	</div>
	<div>
		<%= f.text_field :twitter %>
	</div>

	<br/>
	<div class="actions">
		<%= f.submit "Sign up", :class=>"btn btn-primary" %>
	</div>

<% end %>

app/views/users/show.html.erb
<h3> User Profile </h3>

<div class = "field">
	Username: <%= @user.username %>
</div>

<div class="field">
	Created timestamp: <%= @user.created_at %>
</div>

<p>
	Recent Posts:
	<% @posts.each do |post| %>
		<ul>
			<li><%= post.title %></li>
		</ul>
	<% end %>
</p>

<p>
	Recent Comments:
	<% @comments.each do |comment| %>
		<ul>
			<li><%= comment.content %></li>
		</ul>
	<% end %>	

</p>

<p>
	Recent Votes:
	<% @votes.each do |vote| %>
		<ul>
			<li><%= vote.post.title %></li>
		</ul>
	<% end %>	

</p>

<p>
	Twitter Handle:
	<%= @user.twitter.to_s %>

	<% Twitter.user_timeline(@user.twitter.to_s).last(10).each do |tweet| %>
		<ul>
			<li><%= tweet.text %></li>
		</ul>

	<% end %>

</p>